### ISSUE TITLE
ModuleNotFoundError: No module named 'ipware.ip2'

### ISSUE THREAD

**Issue by rawad1989** [jazzband/django-axes#602] opened 2020-07-01 06:43 UTC
Error with ipware module since it is updated 4 hours ago

ModuleNotFoundError: No module named 'ipware.ip2'

**Comment by KSD-France** [comment] 2020-07-01 06:57
Duplicate of #601.

**Comment by aleksihakli** [comment] 2020-07-03 07:29
Fixed in 5.3.5 where ipware has been locked to suitable version range >=2,<3 for now.

**Closed by aleksihakli** 2020-07-03 07:29 UTC
