### ISSUE TITLE
'install_requires' must be a string or list

### ISSUE THREAD

**Issue by DBejan** [jazzband/django-axes#349] opened 2018-08-01 10:30 UTC
I'm having problems installing axes with pip

Using python 2.7.3, pip 18.0 and setuptools 40.0.0

`$ pip install django-axes`
`Collecting django-axes`
`  Using cached https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz`
`    Complete output from command python setup.py egg_info:`
`    error in django-axes setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`

**Comment by aleksihakli** [comment] 2018-08-02 09:38
Hi @DBejan! Could you post a bit more diagnostic information with verbose output mode from pip? The install_requires [actually is a list of strings](https://github.com/jazzband/django-axes/blob/master/setup.py), but I'm wondering if pip 18 and setuptools 40 have changed the package spec.

**Comment by DBejan** [comment] 2018-08-02 10:50
Sad part is that i had no problems with this on local or qa environments. This error was when deploying to live :(

Some additional details which might help: after posting this I downgraded pip to 10 (same as on qa env) and had the same error. Tried older versions of axes and the most recent one that would install was 4.0.1. however, this one threw `ImportError: No module named backends`, so I had to deactivate it

after retrying to install today:
```
$ pip install -v -I django-axes
Created temporary directory: /tmp/pip-ephem-wheel-cache-qulfbJ
Created temporary directory: /tmp/pip-req-tracker-qoQmUE
Created requirements tracker '/tmp/pip-req-tracker-qoQmUE'
Created temporary directory: /tmp/pip-install-LoXJ3O
Collecting django-axes
  1 location(s) to search for versions of django-axes:
  * https://pypi.org/simple/django-axes/
  Getting page https://pypi.org/simple/django-axes/
  Looking up "https://pypi.org/simple/django-axes/" in the cache
  Current age based on date: 244
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 244
  Analyzing links from page https://pypi.org/simple/django-axes/
    Found link https://files.pythonhosted.org/packages/1d/1d/fb33714043ed80df7d75c1971e84f08308144e9f86197d6e7e9403cb2a6f/django-axes-0.1.0-pre.tar.bz2#sha256=63a7ffa5aad2d84dcd810e89ecd3422bede08f618ee1cd1acde41166695400b0 (from https://pypi.org/simple/django-axes/), version: 0.1.0-pre
    Found link https://files.pythonhosted.org/packages/99/aa/96466aacfe27f10bd49a1fe441e0fc60ba459c7845e84d5a2072f536ca91/django-axes-0.1.0-pre.tar.gz#sha256=7c08eb9e6d9b83bc0898e164627810bf04f712a1a94961ba750571c8af068a5a (from https://pypi.org/simple/django-axes/), version: 0.1.0-pre
    Found link https://files.pythonhosted.org/packages/88/27/25ea0d87f6d294733fd1f0681a49abcee91f93c5699309cbb56bd511e730/django-axes-0.1.0-pre.zip#sha256=946c88fd740b8bd391138b6b309f3c7ed242c0a7550ee9444cc0f221eab63f44 (from https://pypi.org/simple/django-axes/), version: 0.1.0-pre
    Found link https://files.pythonhosted.org/packages/e6/8c/8c2f7f7201c236efb91532e9a3debccb68ae8fdd5f8d18583768cd5be8f0/django-axes-0.1.1-rc1.tar.bz2#sha256=f4308639f40e4dac42758246ee14bf3b4bd6c1caae825ee537e390ad3f044a2e (from https://pypi.org/simple/django-axes/), version: 0.1.1-rc1
    Found link https://files.pythonhosted.org/packages/14/72/b8879ed6b16bfaec5a248d535e46b783cc2a8259d1b54d78dfce240c5f1c/django-axes-0.1.1-rc1.tar.gz#sha256=a5c64ab5d556f95f8040b35cc817933677c43b51b082a43ff8ef9421e979b59f (from https://pypi.org/simple/django-axes/), version: 0.1.1-rc1
    Found link https://files.pythonhosted.org/packages/3f/dd/0d0a6f2e2a49fbdd30abb2af1b9bf9d78641a36aa8ab83daf79d4fe403fd/django-axes-0.1.1-rc1.zip#sha256=7057eae4e7e5c720ff8c75add45079ea5bbc654d328aca88a62e2e9e03b1f46d (from https://pypi.org/simple/django-axes/), version: 0.1.1-rc1
    Found link https://files.pythonhosted.org/packages/28/41/65ce6dee45fbb989f937510c7be193cfa9a01a55fe16f4792cc751857da1/django-axes-1.0.0-rc2.tar.gz#sha256=7976e017ec6c88b805c535d30010fefbe4d64ad4d5407da9e4fcc4854dcde84c (from https://pypi.org/simple/django-axes/), version: 1.0.0-rc2
    Found link https://files.pythonhosted.org/packages/df/ae/f5c03d3063a19f9867153f1d2de09ae3ab9beb8cbe2ee7c0b2e3079b6336/django-axes-1.2.1-rc1.tar.gz#sha256=7b6f2a7aff198c151f4ad8859526e2b6aa19b77a07d61e6713a22b3909fd344b (from https://pypi.org/simple/django-axes/), version: 1.2.1-rc1
    Found link https://files.pythonhosted.org/packages/de/36/b9e044f70ff315ac7026d2fa7e295d70dca1971179ec5a69343325e13539/django-axes-1.2.2-rc1.tar.gz#sha256=56f8a8322e5a672b1d305767a710a23dc95a0530a95d540b3dbda7578aa9f06f (from https://pypi.org/simple/django-axes/), version: 1.2.2-rc1
    Found link https://files.pythonhosted.org/packages/6d/39/d60ccee55345e752b2b36f1bdb372b5948837248d8ffe513be442b5faa36/django-axes-1.2.3-rc1.tar.gz#sha256=9867ac414cc73585f92440aed9f1218dea6d8f31468ee5c3bff2ab55867f8fd4 (from https://pypi.org/simple/django-axes/), version: 1.2.3-rc1
    Found link https://files.pythonhosted.org/packages/1f/1e/00a15981e04b99a93aa20d9b777cdbc8e455168e94f1eb0aeb36a514cc2d/django-axes-1.2.4-rc1.tar.gz#sha256=e24104d03cb60ebf9d57619f043ebf22bc177acf72cbe6a2fa7e5ab26d36f138 (from https://pypi.org/simple/django-axes/), version: 1.2.4-rc1
    Found link https://files.pythonhosted.org/packages/74/a9/5e8998db52709906948563fadfcd248c76fce1041ee66287669097017c4b/django-axes-1.2.5-rc1.tar.gz#sha256=101de9d7cbd180dddc3d9e3af0fd41deaee5ac8b555fb933eda23199b63c6216 (from https://pypi.org/simple/django-axes/), version: 1.2.5-rc1
    Found link https://files.pythonhosted.org/packages/64/1b/38dfcc927e43167e986772e66afabda2dbdeaf2515c09f26cb5b8b221c5b/django-axes-1.2.5.zip#sha256=dec48f9450ba9d848e1de71558e9a0447ed432e43ba74cd45ae53d7ece310515 (from https://pypi.org/simple/django-axes/), version: 1.2.5
    Found link https://files.pythonhosted.org/packages/23/e7/97089b6d965d6fa3e19e0d93dbd53a0fcaeaf7c7fef88a5ecce523ac290c/django-axes-1.2.6.zip#sha256=df9960b1e648e3da9784f56ca0446757f45bd484d39591df163af069e8206560 (from https://pypi.org/simple/django-axes/), version: 1.2.6
    Found link https://files.pythonhosted.org/packages/99/82/32ff17cf078c3b45f4a818926fb32cc642c0c1570f24f15b487c5ff3ce72/django-axes-1.2.7.zip#sha256=8597905cfb2b552bab9af4d5a389b7e04ef963dcfd2ea2a76aeb84096568d075 (from https://pypi.org/simple/django-axes/), version: 1.2.7
    Found link https://files.pythonhosted.org/packages/25/ae/9f0d8ac09a9111da28bd26bcdf2614bb4c6bf7970b3327f15bd1ab898faa/django-axes-1.2.8.zip#sha256=e878b8f02b74e350933903d125cf06ce28847b43c606db68c0fcd91e234d961f (from https://pypi.org/simple/django-axes/), version: 1.2.8
    Found link https://files.pythonhosted.org/packages/f4/a7/486db615d228a058ea75a23a8e5a62b8a3d504ea0091d00ece17416b599d/django-axes-1.2.9.zip#sha256=2bd51fd77f4fdaf6398c14f49a2093e92cf9537ce21501c7a1e6a30cdb0ea244 (from https://pypi.org/simple/django-axes/), version: 1.2.9
    Found link https://files.pythonhosted.org/packages/23/15/51c7e268f8cbb4da24a9f49d18386c03ab9ea30dce69936c0da9b73084d7/django-axes-1.3.0.zip#sha256=1fb1f9566aa60b676d0585d4264237ca9dc6bbccfea3f7ed038f42b3ad345b15 (from https://pypi.org/simple/django-axes/), version: 1.3.0
    Found link https://files.pythonhosted.org/packages/2b/c5/99eafa88281623aa79f8c1c7744dd1005b73b45929dff3daf95674f8febc/django-axes-1.3.1.zip#sha256=1963e2e383f1d2da6d04206074d20c46b41110101da3cfa643be5fc8bab72b60 (from https://pypi.org/simple/django-axes/), version: 1.3.1
    Found link https://files.pythonhosted.org/packages/08/71/d3ede31695d3f530c16a7dd4af6804e176d453a29b702e4702975d780f22/django-axes-1.3.2.zip#sha256=a21a7a10dff81df179e8d5fec6291f9b0ce577d3b16072bce812544dde27c7ff (from https://pypi.org/simple/django-axes/), version: 1.3.2
    Found link https://files.pythonhosted.org/packages/ca/84/35025b469b8ae200cb54309e0fff661efb750ad55a8d0664c2dc77cf5c1b/django-axes-1.3.4.dev0.tar.gz#sha256=633cb575bc90699eee01c81f810e4cf5f2f287f234b43ee3542e27638a437bb4 (from https://pypi.org/simple/django-axes/), version: 1.3.4.dev0
    Found link https://files.pythonhosted.org/packages/e2/e5/27a05632fd526bffcce57b7557987614cbfdde6444236b95b54c13e319c4/django-axes-1.3.4.zip#sha256=87cc621fe0c3d0bb2a634a1aacd9ce2cd2f8b4eb980887576b3abdbb6d056883 (from https://pypi.org/simple/django-axes/), version: 1.3.4
    Found link https://files.pythonhosted.org/packages/b7/26/9b36c74e250307141447a9ad5ba3fdc94308327e84ae879eebcdf7736cc4/django-axes-1.3.5.zip#sha256=f9dbeb498d13b20bd2345d0c19bbec133f1ebfaa20fde1fc68946bba9aa225fd (from https://pypi.org/simple/django-axes/), version: 1.3.5
    Found link https://files.pythonhosted.org/packages/e2/13/85731549867afd1235d49c8eb39512b4a1c773c9aabc6cc87ed5d59b608d/django-axes-1.3.6.tar.gz#sha256=79e15f6b25430c4fd52a5459379640dfcfde5d3eab9e11f62ccdc71406cdb530 (from https://pypi.org/simple/django-axes/), version: 1.3.6
    Found link https://files.pythonhosted.org/packages/6a/9f/03a25de32bc0bb6f4f191fc635d017adbbf6cd32339522f5db6d7aff905c/django-axes-1.3.7.zip#sha256=ab1d8651d396a2d711c0cb4d78d44e166f0b6ffa1b6bd360a110c7ae0c7df9cd (from https://pypi.org/simple/django-axes/), version: 1.3.7
    Found link https://files.pythonhosted.org/packages/3f/35/e68e6af5b1c3f3e190e696b4a08c89929b1512f89e5c68ac1a062ca61b34/django-axes-1.3.8.zip#sha256=6acecc740c15793f7873bfa2c8703475cf9343d15c3cfd6d6d35313c3f9faf24 (from https://pypi.org/simple/django-axes/), version: 1.3.8
    Found link https://files.pythonhosted.org/packages/8a/8c/6e2049931dfeff0b1124c187504cf6153163638c2a145ac7082c643e5eaf/django-axes-1.3.9.zip#sha256=35fce26fdc1c2f74882ae1a6f105fc33f1c4d486fa02b0680e61ec3e7508d49b (from https://pypi.org/simple/django-axes/), version: 1.3.9
    Found link https://files.pythonhosted.org/packages/41/bb/983aa9b104aecc13022d519a3b5b88d791fedc81d18dad8e677e4da0937f/django-axes-1.4.0.zip#sha256=59a6a3fcc124cd83957971830e6cc9a2d706879e4c3f11db850d6e9951decdbb (from https://pypi.org/simple/django-axes/), version: 1.4.0
    Found link https://files.pythonhosted.org/packages/3d/27/a3c34c2fbd31e79244eeab436787380c18068bc23f380fbc0ab7b23e2b9b/django-axes-1.5.0.zip#sha256=3c8c503762b955706b1af32b0d046c6c5f97eb4509a869f4c429b1909c9c1237 (from https://pypi.org/simple/django-axes/), version: 1.5.0
    Found link https://files.pythonhosted.org/packages/8d/03/a4f1427d7a27f4f2f4280ce5917e48ebbbe2dc04f8b69e5f8ab5e5d4d438/django-axes-1.6.0.tar.gz#sha256=695268ab0f64b5466e45ff5dc253ff78722ad0799157f88de43a0cc49a656569 (from https://pypi.org/simple/django-axes/), version: 1.6.0
    Found link https://files.pythonhosted.org/packages/9e/70/abc92a479f857af56dd1ca674b7c9376d2eb196df06c462603f566de4643/django-axes-1.6.1.tar.gz#sha256=eb6fa62a5c8f8baaf2d4537bb6748d89633d6ced401c75326b6f9e5283028724 (from https://pypi.org/simple/django-axes/), version: 1.6.1
    Found link https://files.pythonhosted.org/packages/84/6a/1c73270ace8108ef7f18a33f607217267fec61a87bb259e96625099d155b/django-axes-1.7.0.tar.gz#sha256=456db72a2bc214e641ac9ceb17b7b2b36ea5d7fb43b3c7a8c3bacacdf7766433 (from https://pypi.org/simple/django-axes/), version: 1.7.0
    Found link https://files.pythonhosted.org/packages/5b/00/e96be2a47978d820f60c60c9d511097fe1885231473fa440ff69b226d740/django-axes-2.0.0.tar.gz#sha256=8708f1d61d6cc3b9379a9d76c61644de78ed25d3aff55cf74d11edb7e728ec96 (from https://pypi.org/simple/django-axes/), version: 2.0.0
    Found link https://files.pythonhosted.org/packages/fd/0a/d8104755c3034e2e5c5409ebf9b7ca60398dfedee70209456ab700b5bc75/django-axes-2.1.0.tar.gz#sha256=bf40eb9b6d21096bd8f02128c7cad20da9a484cb4bd9c7066fc9e63bd1f38faf (from https://pypi.org/simple/django-axes/), version: 2.1.0
    Found link https://files.pythonhosted.org/packages/13/4d/585823d41809b3f97560c97d7cd9a018c54d671fc761eeef644f74ffd22c/django-axes-2.2.0.tar.gz#sha256=83a966dfddb9c8cfb5478e2c960a77420570aa775144c837528604e93255d527 (from https://pypi.org/simple/django-axes/), version: 2.2.0
    Found link https://files.pythonhosted.org/packages/04/b9/2959747607a0d824dde19fb3c3b9b54ce2950aae3a913229e82b092e28ee/django-axes-2.3.0.tar.gz#sha256=8020e1723b2c31a009d00e5d7ce80459df83381f7b78e2290548447c901671e8 (from https://pypi.org/simple/django-axes/), version: 2.3.0
    Found link https://files.pythonhosted.org/packages/50/00/9e8f2732df65dd33acc6326ebc27ca59a2b0d1ecca88db46172a9059a403/django_axes-2.3.0-py2-none-any.whl#sha256=92b3336216d77fd0e3b6ed3e5e78f11020129885568f58b45b5e38d025bee56e (from https://pypi.org/simple/django-axes/), version: 2.3.0
    Found link https://files.pythonhosted.org/packages/a0/22/9dc2d1d028364dfccf195fa3e5d92052c056b903e64708d8816c79a9f406/django-axes-2.3.1.tar.gz#sha256=b1c8a8a0559f421edf7b83c73319a93448c88d00968a6006766cd5428df6f5c2 (from https://pypi.org/simple/django-axes/), version: 2.3.1
    Found link https://files.pythonhosted.org/packages/50/5f/12749156689ecff2a97e74295a13543d87b6a565e90a27dd2517283ee988/django-axes-2.3.2.tar.gz#sha256=7ba74b1028ec325481e526591f26e73540d0da5dff82105c8baba3a546c09f98 (from https://pypi.org/simple/django-axes/), version: 2.3.2
    Found link https://files.pythonhosted.org/packages/47/1c/956fb482004f92f0b4978251a70142c11ba3ffb3f56a5ee9373efefaca8f/django-axes-2.3.3.tar.gz#sha256=408344fe851d468df617d28809cf8c4196e33138744b5b9af5f8b13d0a74aca5 (from https://pypi.org/simple/django-axes/), version: 2.3.3
    Found link https://files.pythonhosted.org/packages/f5/0b/a98ca65c87d82ea35fa571bc64d984a935d575ddab6614581eb89d730fed/django-axes-3.0.1.tar.gz#sha256=7ebe4fd370c48c901db69914ef20630fa1d8da1f37c5d75ea305160cdffcd5a8 (from https://pypi.org/simple/django-axes/), version: 3.0.1
    Found link https://files.pythonhosted.org/packages/ce/16/73992a6d44f1e7bd3374d55d01854d3b1ee2ca711e4e45e312d6f9660e27/django-axes-3.0.2.tar.gz#sha256=214c62a8a936845fa0c5e55bdace96aaec9aa81b97a2b673ed49fbbe866f8f1b (from https://pypi.org/simple/django-axes/), version: 3.0.2
    Found link https://files.pythonhosted.org/packages/61/e9/87e34887040b699b71cc8f765e745039c828f29a899d003e248d588f1a39/django-axes-3.0.3.tar.gz#sha256=5a5af294353e4db676cc6ece5d028d2043bdcf6f844eaefa74923c306ef69f26 (from https://pypi.org/simple/django-axes/), version: 3.0.3
    Skipping link https://files.pythonhosted.org/packages/a7/6e/267f6b1f29b2d5d1a3d038a03eb1ad9f4e9e238fb4379bc327da8b8cf59f/django_axes-3.0.3-py3-none-any.whl#sha256=70d60d38ea60b440a9ab9341d38729c284dc28c0fdd648803cc70dcbb69995de (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/ba/48/981a48762558b4f518318e6c342ad0e3fc7294cef59cc496472666385eab/django-axes-4.0.0.tar.gz#sha256=65f2892a1e768f180e3e083adb56ad1058e75c22472d386b3777fe3841e32fa6 (from https://pypi.org/simple/django-axes/), version: 4.0.0
    Skipping link https://files.pythonhosted.org/packages/ce/b8/5be78ae7c927943b3bfd9165bfd96530d10a60669793a3ab3afdb162735c/django_axes-4.0.0-py3-none-any.whl#sha256=d816671816763b47260c1e9de143ffec5990981f084085841b341626ae98651a (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/35/36/f7410c8459ad329a6c2b9b0dd68f18112aa64c343f9e3ad2729080c37c43/django-axes-4.0.1.tar.gz#sha256=ee110c444249c1fb9ef4b349a0ef6c5b82f85fff4cc2bfbb844d5670413dccb1 (from https://pypi.org/simple/django-axes/), version: 4.0.1
    Skipping link https://files.pythonhosted.org/packages/2b/1e/7eee3e17b0000a9101316e4e177092bcbb96a99aae88f60f5fc2a17d499e/django_axes-4.0.1-py3-none-any.whl#sha256=f28272d4145f7bef94a58b8bea40b782487ed210855e406dd915ba50184f4138 (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/10/e8/a1bf7d62a4fedc33c06acbb55aa3c4738e0c5edf7aac64f07c3b4eed885a/django-axes-4.0.2.tar.gz#sha256=aca98b45de63dc7aae2ec74be0b720e08f70e2cff3df577009099169d0be0187 (from https://pypi.org/simple/django-axes/), version: 4.0.2
    Skipping link https://files.pythonhosted.org/packages/da/e3/61c92dc2dc70381612beb0aa6e7da6e6ae886c20cad7dea52d984c283a19/django_axes-4.0.2-py3-none-any.whl#sha256=75747d30c08b89457bf67c672e2dfbab7d0d46bac1e90492dc743e2d0a44f1ec (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/b6/ec/ef1d5cf15821699291725b022fc37ef0a9909e5ba2352c64d37fe5f16771/django-axes-4.1.0.tar.gz#sha256=563882a99deb67e826575152ab8caa3b77e15bc3298a7a44674fba587d57fbc0 (from https://pypi.org/simple/django-axes/), version: 4.1.0
    Skipping link https://files.pythonhosted.org/packages/cb/a7/f76531fa83f2a51f7beb241e455c63fe8000909f269161ddc304319b0ce4/django_axes-4.1.0-py3-none-any.whl#sha256=719c2fc8ea4d6a20300f474ba4cbd772599f6849a07a006ba2f2155813fbe713 (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/b2/1d/a5629deaf4f5f273c91f24b75de3a9b23e3bc21354a5263f5db5cb42aae1/django-axes-4.2.0.tar.gz#sha256=047154340116115baac37e839fb02ef85efe43e73d702deb664c4613228a81c9 (from https://pypi.org/simple/django-axes/), version: 4.2.0
    Skipping link https://files.pythonhosted.org/packages/cc/d6/1335f16f139265d7aa591e498522584e531294ba6e024774c7bcfe40dacd/django_axes-4.2.0-py3-none-any.whl#sha256=23498fe32fa74ad4ed2efba4e6d9c919becdcb3548546cbae24c19140932da31 (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/34/3f/7c1fd2413e29a4506a276063a7582dc4833f3d7643fd29ce890f895dc92b/django-axes-4.2.1.tar.gz#sha256=0cd70176ac86be83e9f0b78efa8c34cd83b59a2a4355dc884ed5f574c026b0ed (from https://pypi.org/simple/django-axes/), version: 4.2.1
    Skipping link https://files.pythonhosted.org/packages/4e/79/b1adc60a571f204102a94d42210ecce2a29b0440e67d84ca35dc0ee35ea2/django_axes-4.2.1-py3-none-any.whl#sha256=4b5814684a479685e67a66f00a335729afa247ec89141f4b08b03d8693f88b9e (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/9f/8c/fb483becfce8f2bf8c7ae31c209f5ed5df6655181f45b621c28c5fb32167/django-axes-4.3.1.tar.gz#sha256=403b2c5b002a4a64a836000843f8eb6f0c418aa889f54fe260e358be84c5865a (from https://pypi.org/simple/django-axes/), version: 4.3.1
    Skipping link https://files.pythonhosted.org/packages/9a/32/20ae7663f058a6a3b5bfe3ba3b6cf5317c2e476f85f8dbaf9abb350ae6d6/django_axes-4.3.1-py3-none-any.whl#sha256=c955cfd24f92de0aa4895fa7e2b8356cf6ef36dde744ffb0f41967d220a38d44 (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz#sha256=155e12f95d0691ac15fe68c7274752356c371df93e8ac97bd1c1629ef682cf50 (from https://pypi.org/simple/django-axes/), version: 4.4.0
    Skipping link https://files.pythonhosted.org/packages/c9/ca/c7d126276104431c5fbdef1f0b409f23e5558f21e5996a41660e57599d89/django_axes-4.4.0-py3-none-any.whl#sha256=4129f6fa089778a4be11c372e3398e85946a369ad3b9a6a642bcce774db81f4a (from https://pypi.org/simple/django-axes/); it is not compatible with this Python
  Using version 4.4.0 (newest of versions: 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 3.0.1, 3.0.2, 3.0.3, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.2.0, 4.2.1, 4.3.1, 4.4.0)
  Created temporary directory: /tmp/pip-unpack-by9gla
  Looking up "https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz" in the cache
  Current age based on date: 88537
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 88537
  Using cached https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz#sha256=155e12f95d0691ac15fe68c7274752356c371df93e8ac97bd1c1629ef682cf50 (from https://pypi.org/simple/django-axes/)
  Added django-axes from https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz#sha256=155e12f95d0691ac15fe68c7274752356c371df93e8ac97bd1c1629ef682cf50 to build tracker '/tmp/pip-req-tracker-qoQmUE'
  Running setup.py (path:/tmp/pip-install-LoXJ3O/django-axes/setup.py) egg_info for package django-axes
    Running command python setup.py egg_info
    error in django-axes setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
Cleaning up...
  Removing source in /tmp/pip-install-LoXJ3O/django-axes
Removed django-axes from https://files.pythonhosted.org/packages/4b/98/598edf58258ca7f6836dd0cac66866315c0914f754747da0595b45294bfa/django-axes-4.4.0.tar.gz#sha256=155e12f95d0691ac15fe68c7274752356c371df93e8ac97bd1c1629ef682cf50 from build tracker '/tmp/pip-req-tracker-qoQmUE'
Removed build tracker '/tmp/pip-req-tracker-qoQmUE'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-LoXJ3O/django-axes/
Exception information:
Traceback (most recent call last):
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 636, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/liferes/life/local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-LoXJ3O/django-axes/
```

**Comment by dokterbob** [comment] 2018-08-31 10:27
I'm hitting the same problem, using:
* django-axes 4.3.1 and 4.4.0
* Python 2.7.13
* setuptools 18.2
* pip 18.0, 10.0.1
* pipenv 2018.7.1

Upgrading setuptools to 40.2.0 solved the problem.

**Comment by DBejan** [comment] 2018-08-31 10:44
Upgraded setuptools to 40.2.0 and still got the same result

**Comment by markddavidoff** [comment] 2018-09-28 21:13
@DBejan I am unable to reproduce, from my research it does seem to be a bug with setuptools? Were you able to resolve this? can you give us a `pip freeze` output please?

**Comment by DBejan** [comment] 2018-10-01 06:11
I remembered what i used to do before pip and installed it manually. Not an ideal solution, I know, but it worked.

Here's the pip freeze:
```
ansicolors==1.0.2
backports.shutil-get-terminal-size==1.0.0
boto==2.48.0
certifi==2018.4.16
chainmap==1.0.2
chardet==3.0.4
codegen==1.0
combomethod==1.0.6
decorator==4.1.1
Django==1.11.3
django-appconf==1.0.2
django-axes==4.0.1
django-braces==1.8.1
django-ckeditor==4.4.6
django-ipware==2.1.0
django-oauth-toolkit==0.10.0
django-recaptcha2==1.0.3
django-robots==3.1.0
django-tinymce==2.6.0
django-widget-tweaks==1.3
djangorestframework==3.6.3
enum34==1.1.6
gunicorn==19.7.1
idna==2.7
ipython==5.7.0
ipython-genutils==0.2.0
mementos==1.2.1
MySQL-python==1.2.5
nulltype==2.2.4
oauthlib==1.0.3
olefile==0.44
options==1.4.3
path.py==8.1.2
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
prompt-toolkit==1.0.14
psycopg2==2.5.4
ptyprocess==0.5.2
Pygments==2.2.0
pytz==2017.2
requests==2.19.1
say==1.4.2
scandir==1.5
simplegeneric==0.8.1
simplere==1.2.8
singleton-admin==1.0.0
six==1.10.0
sorl-thumbnail==12.4a1
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
```

**Comment by markddavidoff** [comment] 2018-10-18 18:15
Closing as user found a workaround and I could not reproduce

**Closed by markddavidoff** 2018-10-18 18:15 UTC

**Comment by markddavidoff** [comment] 2018-10-25 21:42
For the Record, I was actually able to reproduce locally with a virtualenv with  setuptools==12.0.5. Upgrading setuptools  fixed the issue
