### ISSUE TITLE
axes_locked_out variable not caught on response in axes middleware __call__ function

### ISSUE THREAD

**Issue by tushar2407** [jazzband/django-axes#729] opened 2021-03-29 21:59 UTC
Hi,
I am a web-dev using your library in one of my projects and working with rest-auth, I encountered that the axes_locked_out variable that was being updated in user_login_failed function of database.py, was not caught in __call__ function of the middleware of django-axes.
I am willing to work on this issue as I found a workaround with your working code.

**Comment by aleksihakli** [comment] 2021-04-06 17:10
Hi @tushar2407. If you have more information on the issue we appreciate any insight you can give. If you have a fix for it, please feel free to open a PR!

**Comment by aleksihakli** [comment] 2021-06-05 15:59
Might be a duplicate of #750

**Closed** 2021-10-12 06:46 UTC
Labels: needs clarification
